services:
  database:
    image: postgres:16.0
    volumes:
      - postgres-data-store:/var/lib/postgresql/data/
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
  backend:
    build: ./backend
    command: uwsgi --ini uwsgi.ini
    volumes:
      - ./backend:/app
      - uwsgi-socket-directory:/run
    environment:
      - POSTGRES_NAME=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    depends_on:
      - database
  backend-daphne:
    build: ./backend
    command: daphne -b 0.0.0.0 -p 8000 backend.asgi:application
    volumes:
      - ./backend:/app
    environment:
      - POSTGRES_NAME=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    depends_on:
      - database
  frontend:
    build: ./frontend
    command: npm run dev
    volumes:
      - ./frontend/app:/app/app
      - ./frontend/pages:/app/pages
    depends_on:
      - database
  webserver:
    build: ./webserver
    volumes:
      - uwsgi-socket-directory:/run
      - ./backend/static:/app/static
      - ./backend/media:/app/media
    ports:
      - "8080:8080"
    depends_on:
      - backend
      - backend-daphne
      - frontend

volumes:
  postgres-data-store:
  uwsgi-socket-directory:
