services:
  database:
    image: postgres:16.0-bookworm
    volumes:
      - postgres-data-store:/var/lib/postgresql/data/
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
  backend:
    build: ./backend
    command: uwsgi --ini uwsgi.ini
    volumes:
      - ./backend:/app
      - uwsgi-socket-directory:/run
    environment:
      - POSTGRES_NAME=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    depends_on:
      - database
  backend-gunicorn:
    build: ./backend
    command: gunicorn backend.asgi -w 2 -b 0.0.0.0:8000 -k uvicorn.workers.UvicornWorker --log-level=debug
    volumes:
      - ./backend:/app
    environment:
      - POSTGRES_NAME=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    depends_on:
      - database
  frontend:
    build: ./frontend
    command: npm start
    volumes:
      - ./frontend/app:/app/app
      - ./frontend/pages:/app/pages
    depends_on:
      - database
  webserver:
    build: ./webserver
    volumes:
      - uwsgi-socket-directory:/run
      - ./backend/static:/app/static
      - ./backend/media:/app/media
    ports:
      - "8080:8080"
    depends_on:
      - backend
      - backend-gunicorn
      - frontend

volumes:
  postgres-data-store:
  uwsgi-socket-directory:
